server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PASSWORD}